language: R
cache: packages

before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown@fix/examples-dontshow")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::clean_site(); pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  skip_cleanup: false
  on:
    all_branches: true

sudo: false

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
  - gh-pages
  - /.*/
