
globalVariables(
  c(
    ".",
    "ballot_name",
    "candidate_id",
    "categories",
    "endpoint",
    "endpoint_input_mapping_nested",
    "first_name",
    "input",
    "last_name",
    "middle_name",
    "name",
    "nick_name",
    "office_id",
    "office_level_id",
    "parent_id",
    "rating",
    "rating_id",
    "rating_name",
    "rating_text",
    "sig_id",
    "suffix",
    "timespan",
    "title"
  )
)
